# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b931d21b0a84787a7f96d8eced9442fa1e0862fbb4de82273dc8ea313e4187de553787c5e83bf62e912d27b6313e5e7da68465ce42b37a97a0de7c426a6284d

test:
  secret_key_base: 4c72348de07afccf54c200be6e589801b4d63716cef8470141f79b4a893dc637fa4ff481ee55101263f9da150e39705d7cf7ebf2dc3c5a84fd042f5936dd8163

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
